### ISSUE TITLE
grafana dashboard

### ISSUE THREAD

**Issue by balajeek** [chvvkumar/apex#1]
Hi, thanks for the idea I am into home automation stuff and bumped into your article on reddit for apex with home assistant. thats cool.  

I already had influxdb and grafana in my setup, so I setup telegraf and pasted the config as you had mentioned in telegraf config.

rather than me creating the grafana dashboard myself i thought i will import your dashboard which i did but it NO DATA
also the json file does not look like it have every thing as i had seen in the screenshot on your reddit thread.

I queried influxdb and i see the telegraf database and measurements.
I don't see any errors on influxdb or telegraf.

So its just the grafana part I am trying to work it out.
btw i use the EB832 apex setup.

if you get a chance help me out. thanks again

**Comment by chvvkumar** [comment]
Can you post your Grafana JSON? I will take a look at it. Did you change the dashboard's source database to point to your own influxdb instance?
