### ISSUE TITLE
No Tank Skimmer or Tank Return values in Grafana

### ISSUE THREAD

**Issue by mauriceatkinson** [chvvkumar/apex#2]
I have used your direction to import data from my apex controller into Home Assistant.  There are no errors in telegraf and Influxdb shows values for tank skimmers.  However in Grafana i just see no data.

I have run the status.xml request to the apex and I see data values but no values are being displayed in Grafana.

I am making a grafana request showing default database, neptune_apex, name, T15_skimmer_P which results in no data.  The same query in influxdb shows data values.

**Comment by chvvkumar** [comment]
> I have used your direction to import data from my apex controller into Home Assistant. There are no errors in telegraf and Influxdb shows values for tank skimmers. However in Grafana i just see no data.
> 
> I have run the status.xml request to the apex and I see data values but no values are being displayed in Grafana.
> 
> I am making a grafana request showing default database, neptune_apex, name, T15_skimmer_P which results in no data. The same query in influxdb shows data values.

Did you create the appropriate panels in Grafana for those sensors? Unfortunately I don't have the same setup but you can copy an existing panel and change what metric it shows within Grafana to create your own panels.

**Comment by mauriceatkinson** [comment]
Sorry my issue as made a mistake with my grafana queries.  Love your solution as very easy to use!!
